### ISSUE TITLE
Can't run it on windows

### ISSUE THREAD

**Issue by unixino** [maxim-s-barabash/ZebraTrace#5]
Hi
I am on windows 10 machine, Installed python 3.10.5 and latest Qt5.
Can't run the program here is the code 

C:\Users\Kimotio\Desktop\ZebraTrace-master\src>python ZebraTrace.pyw
Traceback (most recent call last):
  File "C:\Users\Kimotio\Desktop\ZebraTrace-master\src\ZebraTrace.pyw", line 17, in <module>
    from zebratrace import zebratrace
  File "C:\Users\Kimotio\Desktop\ZebraTrace-master\src\zebratrace\__init__.py", line 18, in <module>
    from .app import ZQApplication
  File "C:\Users\Kimotio\Desktop\ZebraTrace-master\src\zebratrace\app.py", line 31, in <module>
    from .geom.funcplotter2 import FuncPlotter
  File "C:\Users\Kimotio\Desktop\ZebraTrace-master\src\zebratrace\geom\funcplotter2.py", line 28, in <module>
    sys.setcheckinterval(0xfff)
AttributeError: module 'sys' has no attribute 'setcheckinterval'. Did you mean: 'setswitchinterval'?

C:\Users\Kimotio\Desktop\ZebraTrace-master\src>

Please help

**Comment by om-hb** [comment]
Hi,
for me, changing `sys.setcheckinterval(0xfff)` to `sys.setswitchinterval(0xfff)` in **ZebraTrace-master\src\zebratrace\geom\funcplotter2.py** fix the issue (at first glance at least).

**Comment by unixino** [comment]
It works THANK YOU
