### ISSUE TITLE
AttributeError: module 'sys' has no attribute 'setcheckinterval'. Did you mean: 'setswitchinterval'?

### ISSUE THREAD

**Issue by dieterdreist** [maxim-s-barabash/ZebraTrace#6]
```
% python3 --version
Python 3.10.6

% python3 ZebraTrace.pyw

Traceback (most recent call last):
  File "ZebraTrace/src/ZebraTrace.pyw", line 17, in <module>
    from zebratrace import zebratrace
  File "ZebraTrace/src/zebratrace/__init__.py", line 18, in <module>
    from .app import ZQApplication
  File "ZebraTrace/src/zebratrace/app.py", line 31, in <module>
    from .geom.funcplotter2 import FuncPlotter
  File "ZebraTrace/src/zebratrace/geom/funcplotter2.py", line 28, in <module>
    sys.setcheckinterval(0xfff)
AttributeError: module 'sys' has no attribute 'setcheckinterval'. Did you mean: 'setswitchinterval'?
```

**Comment by dieterdreist** [comment]
it seems it was removed in python 3.9 and `setswitchinterval` should be used instead 
https://bugs.python.org/issue37392

**Comment by dieterdreist** [comment]
after commenting the line `sys.setcheckinterval(0xfff)` out, it runs

**Comment by aa022** [comment]
same
